export const API_ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  MISSING_INTERNAL_API_URL: "MISSING_INTERNAL_API_URL",
  MISSING_OAUTH_CLIENT_CONFIG: "MISSING_OAUTH_CLIENT_CONFIG",
  LOGIN_FAILED: "LOGIN_FAILED",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  SIGNUP_VALIDATION_FAILED: "SIGNUP_VALIDATION_FAILED",
  EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",
  SESSION_DELETE_FAILED: "SESSION_DELETE_FAILED",
  ORGANIZATION_FETCH_FAILED: "ORGANIZATION_FETCH_FAILED",
  REFERENCES_FETCH_FAILED: "REFERENCES_FETCH_FAILED",
  INVALID_BACKEND_RESPONSE: "INVALID_BACKEND_RESPONSE",
  INVALID_LOCALE: "INVALID_LOCALE",
  FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
